modLoader = "kotlinforforge"
loaderVersion = "[4,]"
license = "MIT"
[[mods]]
modId = "$id"
version = "$version"
displayName = "$name"
logoFile = "assets/${id}/icon.png"
authors = "$author"
description = "$description"
[[dependencies.$id]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.$id]]
modId = "kotlinforforge"
mandatory = true
ordering = "NONE"
side = "BOTH"
