[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.20.1"
kotlin = "1.8.22"
kotlinx_serialization = "1.5.1"
parchmentmc = "2023.07.23"
minotaur = "2.+"
forge = "1.20.1-47.1.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
kotlinx_serialization_core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx_serialization" }
kotlinx_serialization_json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx_serialization" }
kotlinx_serialization_hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version.ref = "kotlinx_serialization" }
kotlin_reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
parchment = { module = "org.parchmentmc.data:parchment-1.20.1", version.ref = "parchmentmc" }

forge = { module = "net.minecraftforge:forge", version.ref = "forge" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.3.+" }
fabric_loom = { id = "fabric-loom", version = "1.3-SNAPSHOT" }
architectury_loom = { id = "dev.architectury.loom", version = "1.3.+" }
architectury = { id = "architectury-plugin", version = "3.4-SNAPSHOT" }

kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin_plugin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

forge_gradle = { id = "net.minecraftforge.gradle", version = "6.+" }
librarian = { id = "org.parchmentmc.librarian.forgegradle", version = "1.+" }

shadow = { id = "com.github.johnrengelman.shadow", version = "8.+" }
vanilla_gradle = { id = "org.spongepowered.gradle.vanilla", version = "0.2.1-SNAPSHOT" }
