modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "${id}_1_20"
version = "$version"
displayName = "${name}"
logoFile = "icon.png"
authors = "${author}"
description = '''
${description}
'''

[[dependencies.${id}_1_20]]
modId = "neoforge"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}_1_20]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${id}.mixins.1.20.json"
