modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "${id}"
version = "$version"
displayName = "${name}"
logoFile = "icon.png"
authors = "${author}"
description = '''
${description}
'''

[[dependencies.${id}]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "${id}.mixins.json"
