modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "${id}_1_21"
version = "$version"
displayName = "${name}"
logoFile = "icon.png"
authors = "${author}"
description = '''
${description}
'''

[[dependencies.${id}_1_21]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}_1_21]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,1.22)"
ordering = "NONE"
side = "BOTH"
