on:
  push:
    tags: [ '[0-9]+.[0-9]+.[0-9]+' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Execute Gradle build
        # https://github.com/neoforged/NeoGradle/issues/207
        run: ./gradlew publish

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Upload jar
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          changelog: ${{ steps.changelog.outputs.changes }}
          game-versions: |
            [1.19.4, 1.21]
          game-version-filter: releases

          # Only include this section if you wish to publish
          # your assets on Modrinth.1
          modrinth-id: epmEbmF0
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            publish/**/!(*-@(dev|sources|javadoc|common|fabric|neoforge|lexforge)).jar
            publish/**/*-@(dev|sources|javadoc|common|fabric|neoforge).jar

          version: ${{ github.ref_name }}

          loaders: |
            fabric
            neoforge

          dependencies: |
            fabric-language-kotlin
            modmenu(recommended)
            kotlin-for-forge

          java: |
            17
            21

      - name: Upload lexforge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          changelog: ${{ steps.changelog.outputs.changes }}
          game-versions: |
            [1.19.4, 1.21]
          game-version-filter: releases

          # Only include this section if you wish to publish
          # your assets on Modrinth.1
          modrinth-id: epmEbmF0
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            publish/**/*-lexforge.jar
            publish/**/*-@(dev|sources).jar

          version: ${{ github.ref_name }}

          loaders: |
            forge

          dependencies: |
            kotlin-for-forge

          java: |
            17
            21

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
