on:
  push:
    tags: [ '[0-9]+.[0-9]+.[0-9]+' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Execute Gradle build
        run: ./gradlew remapFabricMinecraftIntermediary build

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Upload jar
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          changelog: ${{ steps.changelog.outputs.changes }}

          # Only include this section if you wish to publish
          # your assets on Modrinth.1
          modrinth-id: epmEbmF0
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 1118733
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            build/libs/!(*-@(fabric*|neoforge*|forge*|sources)).jar
            build/libs/*-@(fabric-*|neoforge-*|sources).jar

          version: ${{ github.ref_name }}

          loaders: |
            neoforge
            fabric

          game-versions: |
            1.20.1
            1.21
            1.21.1
          game-version-filter: releases

          dependencies: |
            fabric-language-kotlin
            kotlin-for-forge

          java: |
            17
            21

      - name: Upload lexforge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          changelog: ${{ steps.changelog.outputs.changes }}

          # Only include this section if you wish to publish
          # your assets on Modrinth.1
          modrinth-id: epmEbmF0
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on CurseForge.
          curseforge-id: 1118733
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            build/libs/*-forge-*.jar

          version: ${{ github.ref_name }}

          loaders: |
            forge

          game-versions: |
            1.20.1
          game-version-filter: releases

          dependencies: |
            kotlin-for-forge

          java: |
            17

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
